export const countries = [
  {"name":"Afghanistan","alpha2":"AF","flag":"https://flagcdn.com/w320/af.png"},
  {"name":"Albania","alpha2":"AL","flag":"https://flagcdn.com/w320/al.png"},
  {"name":"Algeria","alpha2":"DZ","flag":"https://flagcdn.com/w320/dz.png"},
  {"name":"Andorra","alpha2":"AD","flag":"https://flagcdn.com/w320/ad.png"},
  {"name":"Angola","alpha2":"AO","flag":"https://flagcdn.com/w320/ao.png"},
  {"name":"Antigua and Barbuda","alpha2":"AG","flag":"https://flagcdn.com/w320/ag.png"},
  {"name":"Argentina","alpha2":"AR","flag":"https://flagcdn.com/w320/ar.png"},
  {"name":"Armenia","alpha2":"AM","flag":"https://flagcdn.com/w320/am.png"},
  {"name":"Australia","alpha2":"AU","flag":"https://flagcdn.com/w320/au.png"},
  {"name":"Austria","alpha2":"AT","flag":"https://flagcdn.com/w320/at.png"},
  {"name":"Azerbaijan","alpha2":"AZ","flag":"https://flagcdn.com/w320/az.png"},
  {"name":"Bahamas","alpha2":"BS","flag":"https://flagcdn.com/w320/bs.png"},
  {"name":"Bahrain","alpha2":"BH","flag":"https://flagcdn.com/w320/bh.png"},
  {"name":"Bangladesh","alpha2":"BD","flag":"https://flagcdn.com/w320/bd.png"},
  {"name":"Barbados","alpha2":"BB","flag":"https://flagcdn.com/w320/bb.png"},
  {"name":"Belarus","alpha2":"BY","flag":"https://flagcdn.com/w320/by.png"},
  {"name":"Belgium","alpha2":"BE","flag":"https://flagcdn.com/w320/be.png"},
  {"name":"Belize","alpha2":"BZ","flag":"https://flagcdn.com/w320/bz.png"},
  {"name":"Benin","alpha2":"BJ","flag":"https://flagcdn.com/w320/bj.png"},
  {"name":"Bhutan","alpha2":"BT","flag":"https://flagcdn.com/w320/bt.png"},
  {"name":"Bolivia","alpha2":"BO","flag":"https://flagcdn.com/w320/bo.png"},
  {"name":"Bosnia and Herzegovina","alpha2":"BA","flag":"https://flagcdn.com/w320/ba.png"},
  {"name":"Botswana","alpha2":"BW","flag":"https://flagcdn.com/w320/bw.png"},
  {"name":"Brazil","alpha2":"BR","flag":"https://flagcdn.com/w320/br.png"},
  {"name":"Brunei","alpha2":"BN","flag":"https://flagcdn.com/w320/bn.png"},
  {"name":"Bulgaria","alpha2":"BG","flag":"https://flagcdn.com/w320/bg.png"},
  {"name":"Burkina Faso","alpha2":"BF","flag":"https://flagcdn.com/w320/bf.png"},
  {"name":"Burundi","alpha2":"BI","flag":"https://flagcdn.com/w320/bi.png"},
  {"name":"Cabo Verde","alpha2":"CV","flag":"https://flagcdn.com/w320/cv.png"},
  {"name":"Cambodia","alpha2":"KH","flag":"https://flagcdn.com/w320/kh.png"},
  {"name":"Cameroon","alpha2":"CM","flag":"https://flagcdn.com/w320/cm.png"},
  {"name":"Canada","alpha2":"CA","flag":"https://flagcdn.com/w320/ca.png"},
  {"name":"Central African Republic","alpha2":"CF","flag":"https://flagcdn.com/w320/cf.png"},
  {"name":"Chad","alpha2":"TD","flag":"https://flagcdn.com/w320/td.png"},
  {"name":"Chile","alpha2":"CL","flag":"https://flagcdn.com/w320/cl.png"},
  {"name":"China","alpha2":"CN","flag":"https://flagcdn.com/w320/cn.png"},
  {"name":"Colombia","alpha2":"CO","flag":"https://flagcdn.com/w320/co.png"},
  {"name":"Comoros","alpha2":"KM","flag":"https://flagcdn.com/w320/km.png"},
  {"name":"Congo (Congo-Brazzaville)","alpha2":"CG","flag":"https://flagcdn.com/w320/cg.png"},
  {"name":"Costa Rica","alpha2":"CR","flag":"https://flagcdn.com/w320/cr.png"},
  {"name":"Croatia","alpha2":"HR","flag":"https://flagcdn.com/w320/hr.png"},
  {"name":"Cuba","alpha2":"CU","flag":"https://flagcdn.com/w320/cu.png"},
  {"name":"Cyprus","alpha2":"CY","flag":"https://flagcdn.com/w320/cy.png"},
  {"name":"Czechia","alpha2":"CZ","flag":"https://flagcdn.com/w320/cz.png"},
  {"name":"Democratic Republic of the Congo","alpha2":"CD","flag":"https://flagcdn.com/w320/cd.png"},
  {"name":"Denmark","alpha2":"DK","flag":"https://flagcdn.com/w320/dk.png"},
  {"name":"Djibouti","alpha2":"DJ","flag":"https://flagcdn.com/w320/dj.png"},
  {"name":"Dominica","alpha2":"DM","flag":"https://flagcdn.com/w320/dm.png"},
  {"name":"Dominican Republic","alpha2":"DO","flag":"https://flagcdn.com/w320/do.png"},
  {"name":"Ecuador","alpha2":"EC","flag":"https://flagcdn.com/w320/ec.png"},
  {"name":"Egypt","alpha2":"EG","flag":"https://flagcdn.com/w320/eg.png"},
  {"name":"El Salvador","alpha2":"SV","flag":"https://flagcdn.com/w320/sv.png"},
  {"name":"Equatorial Guinea","alpha2":"GQ","flag":"https://flagcdn.com/w320/gq.png"},
  {"name":"Eritrea","alpha2":"ER","flag":"https://flagcdn.com/w320/er.png"},
  {"name":"Estonia","alpha2":"EE","flag":"https://flagcdn.com/w320/ee.png"},
  {"name":"Eswatini","alpha2":"SZ","flag":"https://flagcdn.com/w320/sz.png"},
  {"name":"Ethiopia","alpha2":"ET","flag":"https://flagcdn.com/w320/et.png"},
  {"name":"Fiji","alpha2":"FJ","flag":"https://flagcdn.com/w320/fj.png"},
  {"name":"Finland","alpha2":"FI","flag":"https://flagcdn.com/w320/fi.png"},
  {"name":"France","alpha2":"FR","flag":"https://flagcdn.com/w320/fr.png"},
  {"name":"Gabon","alpha2":"GA","flag":"https://flagcdn.com/w320/ga.png"},
  {"name":"Gambia","alpha2":"GM","flag":"https://flagcdn.com/w320/gm.png"},
  {"name":"Georgia","alpha2":"GE","flag":"https://flagcdn.com/w320/ge.png"},
  {"name":"Germany","alpha2":"DE","flag":"https://flagcdn.com/w320/de.png"},
  {"name":"Ghana","alpha2":"GH","flag":"https://flagcdn.com/w320/gh.png"},
  {"name":"Greece","alpha2":"GR","flag":"https://flagcdn.com/w320/gr.png"},
  {"name":"Grenada","alpha2":"GD","flag":"https://flagcdn.com/w320/gd.png"},
  {"name":"Guatemala","alpha2":"GT","flag":"https://flagcdn.com/w320/gt.png"},
  {"name":"Guinea","alpha2":"GN","flag":"https://flagcdn.com/w320/gn.png"},
  {"name":"Guinea-Bissau","alpha2":"GW","flag":"https://flagcdn.com/w320/gw.png"},
  {"name":"Guyana","alpha2":"GY","flag":"https://flagcdn.com/w320/gy.png"},
  {"name":"Haiti","alpha2":"HT","flag":"https://flagcdn.com/w320/ht.png"},
  {"name":"Honduras","alpha2":"HN","flag":"https://flagcdn.com/w320/hn.png"},
  {"name":"Hungary","alpha2":"HU","flag":"https://flagcdn.com/w320/hu.png"},
  {"name":"Iceland","alpha2":"IS","flag":"https://flagcdn.com/w320/is.png"},
  {"name":"India","alpha2":"IN","flag":"https://flagcdn.com/w320/in.png"},
  {"name":"Indonesia","alpha2":"ID","flag":"https://flagcdn.com/w320/id.png"},
  {"name":"Iran","alpha2":"IR","flag":"https://flagcdn.com/w320/ir.png"},
  {"name":"Iraq","alpha2":"IQ","flag":"https://flagcdn.com/w320/iq.png"},
  {"name":"Ireland","alpha2":"IE","flag":"https://flagcdn.com/w320/ie.png"},
  {"name":"Israel","alpha2":"IL","flag":"https://flagcdn.com/w320/il.png"},
  {"name":"Italy","alpha2":"IT","flag":"https://flagcdn.com/w320/it.png"},
  {"name":"Jamaica","alpha2":"JM","flag":"https://flagcdn.com/w320/jm.png"},
  {"name":"Japan","alpha2":"JP","flag":"https://flagcdn.com/w320/jp.png"},
  {"name":"Jordan","alpha2":"JO","flag":"https://flagcdn.com/w320/jo.png"},
  {"name":"Kazakhstan","alpha2":"KZ","flag":"https://flagcdn.com/w320/kz.png"},
  {"name":"Kenya","alpha2":"KE","flag":"https://flagcdn.com/w320/ke.png"},
  {"name":"Kiribati","alpha2":"KI","flag":"https://flagcdn.com/w320/ki.png"},
  {"name":"Kuwait","alpha2":"KW","flag":"https://flagcdn.com/w320/kw.png"},
  {"name":"Kyrgyzstan","alpha2":"KG","flag":"https://flagcdn.com/w320/kg.png"},
  {"name":"Laos","alpha2":"LA","flag":"https://flagcdn.com/w320/la.png"},
  {"name":"Latvia","alpha2":"LV","flag":"https://flagcdn.com/w320/lv.png"},
  {"name":"Lebanon","alpha2":"LB","flag":"https://flagcdn.com/w320/lb.png"},
  {"name":"Lesotho","alpha2":"LS","flag":"https://flagcdn.com/w320/ls.png"},
  {"name":"Liberia","alpha2":"LR","flag":"https://flagcdn.com/w320/lr.png"},
  {"name":"Libya","alpha2":"LY","flag":"https://flagcdn.com/w320/ly.png"},
  {"name":"Liechtenstein","alpha2":"LI","flag":"https://flagcdn.com/w320/li.png"},
  {"name":"Lithuania","alpha2":"LT","flag":"https://flagcdn.com/w320/lt.png"},
  {"name":"Luxembourg","alpha2":"LU","flag":"https://flagcdn.com/w320/lu.png"},
  {"name":"Madagascar","alpha2":"MG","flag":"https://flagcdn.com/w320/mg.png"},
  {"name":"Malawi","alpha2":"MW","flag":"https://flagcdn.com/w320/mw.png"},
  {"name":"Malaysia","alpha2":"MY","flag":"https://flagcdn.com/w320/my.png"},
  {"name":"Maldives","alpha2":"MV","flag":"https://flagcdn.com/w320/mv.png"},
  {"name":"Mali","alpha2":"ML","flag":"https://flagcdn.com/w320/ml.png"},
  {"name":"Malta","alpha2":"MT","flag":"https://flagcdn.com/w320/mt.png"},
  {"name":"Marshall Islands","alpha2":"MH","flag":"https://flagcdn.com/w320/mh.png"},
  {"name":"Mauritania","alpha2":"MR","flag":"https://flagcdn.com/w320/mr.png"},
  {"name":"Mauritius","alpha2":"MU","flag":"https://flagcdn.com/w320/mu.png"},
  {"name":"Mexico","alpha2":"MX","flag":"https://flagcdn.com/w320/mx.png"},
  {"name":"Micronesia","alpha2":"FM","flag":"https://flagcdn.com/w320/fm.png"},
  {"name":"Moldova","alpha2":"MD","flag":"https://flagcdn.com/w320/md.png"},
  {"name":"Monaco","alpha2":"MC","flag":"https://flagcdn.com/w320/mc.png"},
  {"name":"Mongolia","alpha2":"MN","flag":"https://flagcdn.com/w320/mn.png"},
  {"name":"Montenegro","alpha2":"ME","flag":"https://flagcdn.com/w320/me.png"},
  {"name":"Morocco","alpha2":"MA","flag":"https://flagcdn.com/w320/ma.png"},
  {"name":"Mozambique","alpha2":"MZ","flag":"https://flagcdn.com/w320/mz.png"},
  {"name":"Myanmar","alpha2":"MM","flag":"https://flagcdn.com/w320/mm.png"},
  {"name":"Namibia","alpha2":"NA","flag":"https://flagcdn.com/w320/na.png"},
  {"name":"Nauru","alpha2":"NR","flag":"https://flagcdn.com/w320/nr.png"},
  {"name":"Nepal","alpha2":"NP","flag":"https://flagcdn.com/w320/np.png"},
  {"name":"Netherlands","alpha2":"NL","flag":"https://flagcdn.com/w320/nl.png"},
  {"name":"New Zealand","alpha2":"NZ","flag":"https://flagcdn.com/w320/nz.png"},
  {"name":"Nicaragua","alpha2":"NI","flag":"https://flagcdn.com/w320/ni.png"},
  {"name":"Niger","alpha2":"NE","flag":"https://flagcdn.com/w320/ne.png"},
  {"name":"Nigeria","alpha2":"NG","flag":"https://flagcdn.com/w320/ng.png"},
  {"name":"North Korea","alpha2":"KP","flag":"https://flagcdn.com/w320/kp.png"},
  {"name":"North Macedonia","alpha2":"MK","flag":"https://flagcdn.com/w320/mk.png"},
  {"name":"Norway","alpha2":"NO","flag":"https://flagcdn.com/w320/no.png"},
  {"name":"Oman","alpha2":"OM","flag":"https://flagcdn.com/w320/om.png"},
  {"name":"Pakistan","alpha2":"PK","flag":"https://flagcdn.com/w320/pk.png"},
  {"name":"Palau","alpha2":"PW","flag":"https://flagcdn.com/w320/pw.png"},
  {"name":"Panama","alpha2":"PA","flag":"https://flagcdn.com/w320/pa.png"},
  {"name":"Papua New Guinea","alpha2":"PG","flag":"https://flagcdn.com/w320/pg.png"},
  {"name":"Paraguay","alpha2":"PY","flag":"https://flagcdn.com/w320/py.png"},
  {"name":"Peru","alpha2":"PE","flag":"https://flagcdn.com/w320/pe.png"},
  {"name":"Philippines","alpha2":"PH","flag":"https://flagcdn.com/w320/ph.png"},
  {"name":"Poland","alpha2":"PL","flag":"https://flagcdn.com/w320/pl.png"},
  {"name":"Portugal","alpha2":"PT","flag":"https://flagcdn.com/w320/pt.png"},
  {"name":"Qatar","alpha2":"QA","flag":"https://flagcdn.com/w320/qa.png"},
  {"name":"Romania","alpha2":"RO","flag":"https://flagcdn.com/w320/ro.png"},
  {"name":"Russia","alpha2":"RU","flag":"https://flagcdn.com/w320/ru.png"},
  {"name":"Rwanda","alpha2":"RW","flag":"https://flagcdn.com/w320/rw.png"},
  {"name":"Saint Kitts and Nevis","alpha2":"KN","flag":"https://flagcdn.com/w320/kn.png"},
  {"name":"Saint Lucia","alpha2":"LC","flag":"https://flagcdn.com/w320/lc.png"},
  {"name":"Saint Vincent and the Grenadines","alpha2":"VC","flag":"https://flagcdn.com/w320/vc.png"},
  {"name":"Samoa","alpha2":"WS","flag":"https://flagcdn.com/w320/ws.png"},
  {"name":"San Marino","alpha2":"SM","flag":"https://flagcdn.com/w320/sm.png"},
  {"name":"Sao Tome and Principe","alpha2":"ST","flag":"https://flagcdn.com/w320/st.png"},
  {"name":"Saudi Arabia","alpha2":"SA","flag":"https://flagcdn.com/w320/sa.png"},
  {"name":"Senegal","alpha2":"SN","flag":"https://flagcdn.com/w320/sn.png"},
  {"name":"Serbia","alpha2":"RS","flag":"https://flagcdn.com/w320/rs.png"},
  {"name":"Seychelles","alpha2":"SC","flag":"https://flagcdn.com/w320/sc.png"},
  {"name":"Sierra Leone","alpha2":"SL","flag":"https://flagcdn.com/w320/sl.png"},
  {"name":"Singapore","alpha2":"SG","flag":"https://flagcdn.com/w320/sg.png"},
  {"name":"Slovakia","alpha2":"SK","flag":"https://flagcdn.com/w320/sk.png"},
  {"name":"Slovenia","alpha2":"SI","flag":"https://flagcdn.com/w320/si.png"},
  {"name":"Solomon Islands","alpha2":"SB","flag":"https://flagcdn.com/w320/sb.png"},
  {"name":"Somalia","alpha2":"SO","flag":"https://flagcdn.com/w320/so.png"},
  {"name":"South Africa","alpha2":"ZA","flag":"https://flagcdn.com/w320/za.png"},
  {"name":"South Korea","alpha2":"KR","flag":"https://flagcdn.com/w320/kr.png"},
  {"name":"South Sudan","alpha2":"SS","flag":"https://flagcdn.com/w320/ss.png"},
  {"name":"Spain","alpha2":"ES","flag":"https://flagcdn.com/w320/es.png"},
  {"name":"Sri Lanka","alpha2":"LK","flag":"https://flagcdn.com/w320/lk.png"},
  {"name":"Sudan","alpha2":"SD","flag":"https://flagcdn.com/w320/sd.png"},
  {"name":"Suriname","alpha2":"SR","flag":"https://flagcdn.com/w320/sr.png"},
  {"name":"Sweden","alpha2":"SE","flag":"https://flagcdn.com/w320/se.png"},
  {"name":"Switzerland","alpha2":"CH","flag":"https://flagcdn.com/w320/ch.png"},
  {"name":"Syria","alpha2":"SY","flag":"https://flagcdn.com/w320/sy.png"},
  {"name":"Tajikistan","alpha2":"TJ","flag":"https://flagcdn.com/w320/tj.png"},
  {"name":"Tanzania","alpha2":"TZ","flag":"https://flagcdn.com/w320/tz.png"},
  {"name":"Thailand","alpha2":"TH","flag":"https://flagcdn.com/w320/th.png"},
  {"name":"Timor-Leste","alpha2":"TL","flag":"https://flagcdn.com/w320/tl.png"},
  {"name":"Togo","alpha2":"TG","flag":"https://flagcdn.com/w320/tg.png"},
  {"name":"Tonga","alpha2":"TO","flag":"https://flagcdn.com/w320/to.png"},
  {"name":"Trinidad and Tobago","alpha2":"TT","flag":"https://flagcdn.com/w320/tt.png"},
  {"name":"Tunisia","alpha2":"TN","flag":"https://flagcdn.com/w320/tn.png"},
  {"name":"Turkey","alpha2":"TR","flag":"https://flagcdn.com/w320/tr.png"},
  {"name":"Turkmenistan","alpha2":"TM","flag":"https://flagcdn.com/w320/tm.png"},
  {"name":"Tuvalu","alpha2":"TV","flag":"https://flagcdn.com/w320/tv.png"},
  {"name":"Uganda","alpha2":"UG","flag":"https://flagcdn.com/w320/ug.png"},
  {"name":"Ukraine","alpha2":"UA","flag":"https://flagcdn.com/w320/ua.png"},
  {"name":"United Arab Emirates","alpha2":"AE","flag":"https://flagcdn.com/w320/ae.png"},
  {"name":"United Kingdom","alpha2":"GB","flag":"https://flagcdn.com/w320/gb.png"},
  {"name":"United States","alpha2":"US","flag":"https://flagcdn.com/w320/us.png"},
  {"name":"Uruguay","alpha2":"UY","flag":"https://flagcdn.com/w320/uy.png"},
  {"name":"Uzbekistan","alpha2":"UZ","flag":"https://flagcdn.com/w320/uz.png"},
  {"name":"Vanuatu","alpha2":"VU","flag":"https://flagcdn.com/w320/vu.png"},
  {"name":"Vatican City","alpha2":"VA","flag":"https://flagcdn.com/w320/va.png"},
  {"name":"Venezuela","alpha2":"VE","flag":"https://flagcdn.com/w320/ve.png"},
  {"name":"Vietnam","alpha2":"VN","flag":"https://flagcdn.com/w320/vn.png"},
  {"name":"Yemen","alpha2":"YE","flag":"https://flagcdn.com/w320/ye.png"},
  {"name":"Zambia","alpha2":"ZM","flag":"https://flagcdn.com/w320/zm.png"},
  {"name":"Zimbabwe","alpha2":"ZW","flag":"https://flagcdn.com/w320/zw.png"}
];
